name: LyvelyExercise
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.3
  go_router: ^14.3.0
  riverpod: ^2.5.3
  riverpod_annotation: ^2.5.3
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.8
  riverpod_lint: ^2.3.13
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:
  uses-material-design: true

